export const data = {
  updateAt: '2023-12-05 17:05:00',
  year: '2020',
  type: 'legislator-party',
  title: '立法委員選舉（不分區）',
  version: 'v2',
  parties: [
    {
      candNo: 1,
      party: {
        label: '合一行動聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 17515,
      tksRate1: 0.12,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 2,
      party: {
        label: '中華統一促進黨',
        href: '',
        imgSrc: '',
      },
      tks: 32966,
      tksRate1: 0.23,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 3,
      party: {
        label: '親民黨',
        href: '',
        imgSrc: '',
      },
      tks: 518921,
      tksRate1: 3.66,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 4,
      party: {
        label: '安定力量',
        href: '',
        imgSrc: '',
      },
      tks: 94563,
      tksRate1: 0.67,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 5,
      party: {
        label: '台灣基進',
        href: '',
        imgSrc: '',
      },
      tks: 447286,
      tksRate1: 3.16,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 6,
      party: {
        label: '時代力量',
        href: '',
        imgSrc: '',
      },
      tks: 1098100,
      tksRate1: 7.75,
      tksRate2: 8.98,
      seats: 3,
    },
    {
      candNo: 7,
      party: {
        label: '新黨',
        href: '',
        imgSrc: '',
      },
      tks: 147373,
      tksRate1: 1.04,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 8,
      party: {
        label: '喜樂島聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 29324,
      tksRate1: 0.21,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 9,
      party: {
        label: '中國國民黨',
        href: '',
        imgSrc: '',
      },
      tks: 4723504,
      tksRate1: 33.36,
      tksRate2: 38.65,
      seats: 13,
    },
    {
      candNo: 10,
      party: {
        label: '一邊一國行動黨',
        href: '',
        imgSrc: '',
      },
      tks: 143617,
      tksRate1: 1.01,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 11,
      party: {
        label: '勞動黨',
        href: '',
        imgSrc: '',
      },
      tks: 19941,
      tksRate1: 0.14,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 12,
      party: {
        label: '綠黨',
        href: '',
        imgSrc: '',
      },
      tks: 341465,
      tksRate1: 2.41,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 13,
      party: {
        label: '宗教聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 31117,
      tksRate1: 0.22,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 14,
      party: {
        label: '民主進步黨',
        href: '',
        imgSrc: '',
      },
      tks: 4811241,
      tksRate1: 33.98,
      tksRate2: 39.37,
      seats: 13,
    },
    {
      candNo: 15,
      party: {
        label: '台灣民眾黨',
        href: '',
        imgSrc: '',
      },
      tks: 1588806,
      tksRate1: 11.22,
      tksRate2: 13,
      seats: 5,
    },
    {
      candNo: 16,
      party: {
        label: '台灣維新',
        href: '',
        imgSrc: '',
      },
      tks: 11952,
      tksRate1: 0.08,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 17,
      party: {
        label: '台澎黨',
        href: '',
        imgSrc: '',
      },
      tks: 11681,
      tksRate1: 0.08,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 18,
      party: {
        label: '國會政黨聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 40331,
      tksRate1: 0.28,
      tksRate2: 0,
      seats: 0,
    },
    {
      candNo: 19,
      party: {
        label: '台灣團結聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 50435,
      tksRate1: 0.36,
      tksRate2: 0,
      seats: 0,
    },
  ],
}
