export const data = {
  updatedAt: '2024-10-26 23:53:49',
  year: '2024',
  type: 'legislator-mountain',
  title: '立法委員選舉(原住民)',
  version: 'v2',
  districts: [
    {
      districtName: '全國（山地）',
      candidates: [
        {
          candNo: '1',
          name: {
            label: '林瑞霞',
            href: 'https://whoareyou.readr.tw/person/37403',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/37403.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 1958,
          tksRate: 3.88,
          candVictor: false,
        },
        {
          candNo: '2',
          name: {
            label: '蔡永泉',
            href: 'https://whoareyou.readr.tw/person/36789',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36789.jpg',
          },
          party: { label: '台灣團結聯盟', href: '', imgSrc: '' },
          tks: 2188,
          tksRate: 4.33,
          candVictor: false,
        },
        {
          candNo: '3',
          name: {
            label: '張榮藏',
            href: 'https://whoareyou.readr.tw/person/39661',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/39661.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2892,
          tksRate: 5.73,
          candVictor: true,
        },
        {
          candNo: '4',
          name: {
            label: '陳家平',
            href: 'https://whoareyou.readr.tw/person/40212',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40212.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3947,
          tksRate: 7.81,
          candVictor: true,
        },
        {
          candNo: '5',
          name: {
            label: '傅大偉',
            href: 'https://whoareyou.readr.tw/person/36788',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36788.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 5054,
          tksRate: 10.01,
          candVictor: true,
        },
        {
          candNo: '6',
          name: {
            label: '黃盈智',
            href: 'https://whoareyou.readr.tw/person/40214',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40214.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4259,
          tksRate: 8.43,
          candVictor: true,
        },
        {
          candNo: '7',
          name: {
            label: '郭文居',
            href: 'https://whoareyou.readr.tw/person/36551',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36551.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2437,
          tksRate: 4.82,
          candVictor: false,
        },
        {
          candNo: '8',
          name: {
            label: '凌子楚',
            href: 'https://whoareyou.readr.tw/person/36786',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36786.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 2447,
          tksRate: 4.84,
          candVictor: false,
        },
        {
          candNo: '9',
          name: {
            label: '梁樹綸',
            href: 'https://whoareyou.readr.tw/person/43563',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43563.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 2524,
          tksRate: 5.0,
          candVictor: false,
        },
        {
          candNo: '10',
          name: {
            label: '郭定緯',
            href: 'https://whoareyou.readr.tw/person/43562',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43562.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3404,
          tksRate: 6.74,
          candVictor: true,
        },
        {
          candNo: '11',
          name: {
            label: '黃露慧',
            href: 'https://whoareyou.readr.tw/person/40211',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40211.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4292,
          tksRate: 8.5,
          candVictor: true,
        },
        {
          candNo: '12',
          name: {
            label: '林昱孜',
            href: 'https://whoareyou.readr.tw/person/43564',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43564.jpg',
          },
          party: { label: '台灣民眾黨', href: '', imgSrc: '' },
          tks: 870,
          tksRate: 1.72,
          candVictor: false,
        },
        {
          candNo: '13',
          name: {
            label: '張敏琪',
            href: 'https://whoareyou.readr.tw/person/40217',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40217.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3438,
          tksRate: 6.81,
          candVictor: true,
        },
        {
          candNo: '14',
          name: {
            label: '顏色不分藍綠支持性專區顏色田慎節',
            href: 'https://whoareyou.readr.tw/person/43565',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43565.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2813,
          tksRate: 5.57,
          candVictor: true,
        },
        {
          candNo: '15',
          name: {
            label: '吳家慧',
            href: 'https://whoareyou.readr.tw/person/43566',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43566.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 486,
          tksRate: 0.96,
          candVictor: false,
        },
        {
          candNo: '16',
          name: {
            label: '翁渙瑤',
            href: 'https://whoareyou.readr.tw/person/43561',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43561.jpg',
          },
          party: { label: '台灣基進', href: '', imgSrc: '' },
          tks: 1350,
          tksRate: 2.67,
          candVictor: false,
        },
        {
          candNo: '17',
          name: {
            label: '李奕德',
            href: 'https://whoareyou.readr.tw/person/40215',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40215.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2771,
          tksRate: 5.49,
          candVictor: true,
        },
        {
          candNo: '18',
          name: {
            label: '戴寧',
            href: 'https://whoareyou.readr.tw/person/36787',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36787.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 3382,
          tksRate: 6.7,
          candVictor: true,
        },
      ],
    },
  ],
}
