export const data = {
  updateAt: '2023-12-05 17:05:00',
  year: '2020',
  type: 'legislator-mountainIndigenous',
  title: '立法委員選舉（原住民）',
  version: 'v2',
  candidates: [
    {
      candNo: 1,
      name: {
        label: '伍麗華 Saidhai．Tahovecahe',
        href: 'https://whoareyou.readr.tw/person/43997',
        imgSrc: 'http://www.ly.gov.tw/Images/Legislators/100005.jpg',
      },
      party: {
        label: '民主進步黨',
        href: '',
        imgSrc: '',
      },
      tks: 25772,
      tksRate: 17.81,
      candVictor: true,
    },
    {
      candNo: 2,
      name: {
        label: '林曉婷',
        href: 'https://whoareyou.readr.tw/person/36989',
        imgSrc: null,
      },
      party: '',
      tks: 634,
      tksRate: 0.44,
      candVictor: false,
    },
    {
      candNo: 3,
      name: {
        label: '高畹芯',
        href: 'https://whoareyou.readr.tw/person/36990',
        imgSrc: null,
      },
      party: {
        label: '喜樂島聯盟',
        href: '',
        imgSrc: '',
      },
      tks: 577,
      tksRate: 0.4,
      candVictor: false,
    },
    {
      candNo: 4,
      name: {
        label: '高金素梅',
        href: 'https://whoareyou.readr.tw/person/279',
        imgSrc: 'http://www.ly.gov.tw//Images/Legislators/100046.jpg',
      },
      party: '',
      tks: 50501,
      tksRate: 34.89,
      candVictor: true,
    },
    {
      candNo: 5,
      name: {
        label: '張曜羣 Lawpaw Buya',
        href: 'https://whoareyou.readr.tw/person/43047',
        imgSrc: null,
      },
      party: {
        label: '台灣綠黨',
        href: '',
        imgSrc: '',
      },
      tks: 1163,
      tksRate: 0.8,
      candVictor: false,
    },
    {
      candNo: 6,
      name: {
        label: '撒卡伊',
        href: 'https://whoareyou.readr.tw/person/36991',
        imgSrc: null,
      },
      party: {
        label: '台澎黨',
        href: '',
        imgSrc: '',
      },
      tks: 366,
      tksRate: 0.25,
      candVictor: false,
    },
    {
      candNo: 7,
      name: {
        label: '伊斯坦大・貝雅夫・正福 Istanda・Paingav',
        href: 'https://whoareyou.readr.tw/person/43048',
        imgSrc: null,
      },
      party: '',
      tks: 8954,
      tksRate: 6.19,
      candVictor: false,
    },
    {
      candNo: 8,
      name: {
        label: '章正輝 Lemaljiz・Kusaza',
        href: 'https://whoareyou.readr.tw/person/1816',
        imgSrc: null,
      },
      party: {
        label: '中國國民黨',
        href: '',
        imgSrc: '',
      },
      tks: 24305,
      tksRate: 16.79,
      candVictor: false,
    },
    {
      candNo: 9,
      name: {
        label: '錢宥均',
        href: 'https://whoareyou.readr.tw/person/7622',
        imgSrc: null,
      },
      party: {
        label: '安定力量',
        href: '',
        imgSrc: '',
      },
      tks: 1241,
      tksRate: 0.86,
      candVictor: false,
    },
    {
      candNo: 10,
      name: {
        label: '孔文吉',
        href: 'https://whoareyou.readr.tw/person/314',
        imgSrc: 'http://www.ly.gov.tw//Images/Legislators/100001.jpg',
      },
      party: {
        label: '中國國民黨',
        href: '',
        imgSrc: '',
      },
      tks: 25788,
      tksRate: 17.82,
      candVictor: true,
    },
    {
      candNo: 11,
      name: {
        label: '林信義',
        href: 'https://whoareyou.readr.tw/person/1585',
        imgSrc: null,
      },
      party: '',
      tks: 5423,
      tksRate: 3.75,
      candVictor: false,
    },
  ],
}
