export const mockData = {
  summary: {
    range: '全國',
    county: null,
    town: null,
    vill: null,
    profRate: 80.0,
    candidates: [
      {
        canNo: 1,
        name: '陳時中',
        party: '民進黨',
        tksRate: 57.13,
        candVictor: '*',
      },
      {
        canNo: 2,
        name: '蔣萬安',
        party: '國民黨',
        tksRate: 38.61,
        candVictor: ' ',
      },
      {
        canNo: 3,
        name: '黃珊珊',
        party: '民眾黨',
        tksRate: 38.61,
        candVictor: ' ',
      },
    ],
  },
  districts: [
    {
      range: '台北市',
      county: '63000',
      town: null,
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '陳時中',
          party: '民進黨',
          tksRate: 57.13,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '蔣萬安',
          party: '國民黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '黃珊珊',
          party: '民眾黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
      ],
    },
    {
      range: '新北市',
      county: '65000',
      town: null,
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '陳時中',
          party: '民進黨',
          tksRate: 57.13,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '蔣萬安',
          party: '國民黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '黃珊珊',
          party: '民眾黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
      ],
    },
    {
      range: '桃園市',
      county: '68000',
      town: null,
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '陳時中',
          party: '民進黨',
          tksRate: 57.13,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '蔣萬安',
          party: '國民黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '黃珊珊',
          party: '民眾黨',
          tksRate: 38.61,
          candVictor: ' ',
        },
      ],
    },
  ],
}
