// [地圖資料] 公投 全國層級資料
export const data = {
  updatedAt: '2022-11-26 23:53:24',
  is_started: true,
  is_running: false,
  summary: {
    range: '全國',
    county: null,
    town: null,
    vill: null,
    profRate: 58.97,
    agreeRate: 52.96,
    disagreeRate: 47.04,
    adptVictor: 'N',
  },
  districts: [
    {
      range: '連江縣',
      county: '09007',
      town: null,
      vill: null,
      profRate: 63.96,
      agreeRate: 34.42,
      disagreeRate: 65.58,
      adptVictor: 'N',
    },
    {
      range: '金門縣',
      county: '09020',
      town: null,
      vill: null,
      profRate: 37.03,
      agreeRate: 31.17,
      disagreeRate: 68.83,
      adptVictor: 'N',
    },
    {
      range: '宜蘭縣',
      county: '10002',
      town: null,
      vill: null,
      profRate: 61.34,
      agreeRate: 57.11,
      disagreeRate: 42.89,
      adptVictor: 'N',
    },
    {
      range: '新竹縣',
      county: '10004',
      town: null,
      vill: null,
      profRate: 56.08,
      agreeRate: 45.57,
      disagreeRate: 54.43,
      adptVictor: 'N',
    },
    {
      range: '苗栗縣',
      county: '10005',
      town: null,
      vill: null,
      profRate: 64.05,
      agreeRate: 47.01,
      disagreeRate: 52.99,
      adptVictor: 'N',
    },
    {
      range: '彰化縣',
      county: '10007',
      town: null,
      vill: null,
      profRate: 63.07,
      agreeRate: 51.65,
      disagreeRate: 48.35,
      adptVictor: 'N',
    },
    {
      range: '南投縣',
      county: '10008',
      town: null,
      vill: null,
      profRate: 65.13,
      agreeRate: 47.76,
      disagreeRate: 52.24,
      adptVictor: 'N',
    },
    {
      range: '雲林縣',
      county: '10009',
      town: null,
      vill: null,
      profRate: 63.48,
      agreeRate: 56.87,
      disagreeRate: 43.13,
      adptVictor: 'N',
    },
    {
      range: '嘉義縣',
      county: '10010',
      town: null,
      vill: null,
      profRate: 62.28,
      agreeRate: 60.15,
      disagreeRate: 39.85,
      adptVictor: 'N',
    },
    {
      range: '屏東縣',
      county: '10013',
      town: null,
      vill: null,
      profRate: 63.76,
      agreeRate: 57.85,
      disagreeRate: 42.15,
      adptVictor: 'N',
    },
    {
      range: '臺東縣',
      county: '10014',
      town: null,
      vill: null,
      profRate: 59.82,
      agreeRate: 43.38,
      disagreeRate: 56.62,
      adptVictor: 'N',
    },
    {
      range: '花蓮縣',
      county: '10015',
      town: null,
      vill: null,
      profRate: 54.36,
      agreeRate: 41.77,
      disagreeRate: 58.23,
      adptVictor: 'N',
    },
    {
      range: '澎湖縣',
      county: '10016',
      town: null,
      vill: null,
      profRate: 52.17,
      agreeRate: 52.68,
      disagreeRate: 47.32,
      adptVictor: 'N',
    },
    {
      range: '基隆市',
      county: '10017',
      town: null,
      vill: null,
      profRate: 56.46,
      agreeRate: 48.54,
      disagreeRate: 51.46,
      adptVictor: 'N',
    },
    {
      range: '新竹市',
      county: '10018',
      town: null,
      vill: null,
      profRate: 61.43,
      agreeRate: 52.23,
      disagreeRate: 47.77,
      adptVictor: 'N',
    },
    {
      range: '嘉義市',
      county: '10020',
      town: null,
      vill: null,
      profRate: 52.46,
      agreeRate: 56.69,
      disagreeRate: 43.31,
      adptVictor: 'N',
    },
    {
      range: '臺北市',
      county: '63000',
      town: null,
      vill: null,
      profRate: 65.92,
      agreeRate: 51.37,
      disagreeRate: 48.63,
      adptVictor: 'N',
    },
    {
      range: '高雄市',
      county: '64000',
      town: null,
      vill: null,
      profRate: 56.92,
      agreeRate: 58.36,
      disagreeRate: 41.64,
      adptVictor: 'N',
    },
    {
      range: '新北市',
      county: '65000',
      town: null,
      vill: null,
      profRate: 55.31,
      agreeRate: 52.72,
      disagreeRate: 47.28,
      adptVictor: 'N',
    },
    {
      range: '臺中市',
      county: '66000',
      town: null,
      vill: null,
      profRate: 58.24,
      agreeRate: 50.57,
      disagreeRate: 49.43,
      adptVictor: 'N',
    },
    {
      range: '臺南市',
      county: '67000',
      town: null,
      vill: null,
      profRate: 56.67,
      agreeRate: 59.59,
      disagreeRate: 40.41,
      adptVictor: 'N',
    },
    {
      range: '桃園市',
      county: '68000',
      town: null,
      vill: null,
      profRate: 57.83,
      agreeRate: 49.88,
      disagreeRate: 50.12,
      adptVictor: 'N',
    },
  ],
}
