export const mockData = {
  summary: {
    range: '台北市',
    county: '63000',
    town: null,
    vill: null,
    profRate: 80.0,
  },
  districts: [
    {
      range: '台北市 第一選區',
      county: '63000',
      area: '01',
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '吳思瑤',
          party: '無黨籍',
          tksRate: 52.12,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '汪志冰',
          party: '國民黨',
          tksRate: 40.38,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '李婉鈺',
          party: '一邊一國行動黨',
          tksRate: 3.21,
          candVictor: ' ',
        },
      ],
    },
    {
      range: '台北市 第二選區',
      county: '63000',
      area: '02',
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '吳思瑤',
          party: '無黨籍',
          tksRate: 52.12,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '汪志冰',
          party: '國民黨',
          tksRate: 40.38,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '李婉鈺',
          party: '一邊一國行動黨',
          tksRate: 3.21,
          candVictor: ' ',
        },
      ],
    },
    {
      range: '台北市 第三選區',
      county: '63000',
      area: '03',
      vill: null,
      profRate: 80.0,
      candidates: [
        {
          canNo: 1,
          name: '吳思瑤',
          party: '無黨籍',
          tksRate: 52.12,
          candVictor: '*',
        },
        {
          canNo: 2,
          name: '汪志冰',
          party: '國民黨',
          tksRate: 40.38,
          candVictor: ' ',
        },
        {
          canNo: 3,
          name: '李婉鈺',
          party: '一邊一國行動黨',
          tksRate: 3.21,
          candVictor: ' ',
        },
      ],
    },
  ],
}
