// [地圖資料] 不分區立法委員(政黨票) 全國層級資料
export const data = {
  updatedAt: '2022-11-26 23:53:49',
  is_started: true,
  is_running: false,
  summary: {
    range: '全國',
    county: null,
    town: null,
    vill: null,
    type: 'party', // 人工驗證資料用，並未直接用在地圖上
    profRate: 58.97,
    candidates: [
      {
        candNo: '1',
        party: '合一行動聯盟',
        tksRate: 0.17,
        candVictor: ' ',
        tks: 2367,
      },
      {
        candNo: '2',
        party: '中華統一促進黨',
        tksRate: 0.03,
        candVictor: ' ',
        tks: 451,
      },
      {
        candNo: '3',
        party: '親民黨',
        tksRate: 0.03,
        candVictor: ' ',
        tks: 386,
      },
      {
        candNo: '4',
        party: '安定力量',
        tksRate: 0.02,
        candVictor: ' ',
        tks: 256,
      },
      {
        candNo: '5',
        party: '台灣基進',
        tksRate: 0.18,
        candVictor: ' ',
        tks: 2425,
      },
      {
        candNo: '6',
        party: '時代力量',
        tksRate: 42.29,
        candVictor: '*',
        tks: 575590,
      },
    ],
  },
  districts: [
    {
      range: '臺北市',
      county: '63000',
      town: null,
      vill: null,
      type: 'party', // 人工驗證資料用，並未直接用在地圖上
      profRate: 67.7,
      candidates: [
        {
          candNo: '1',
          party: '合一行動聯盟',
          tksRate: 0.17,
          candVictor: ' ',
          tks: 2367,
        },
        {
          candNo: '2',
          party: '中華統一促進黨',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 451,
        },
        {
          candNo: '3',
          party: '親民黨',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 386,
        },
        {
          candNo: '4',
          party: '安定力量',
          tksRate: 0.02,
          candVictor: ' ',
          tks: 256,
        },
        {
          candNo: '5',
          party: '台灣基進',
          tksRate: 0.18,
          candVictor: ' ',
          tks: 2425,
        },
        {
          candNo: '6',
          party: '時代力量',
          tksRate: 42.29,
          candVictor: '*',
          tks: 575590,
        },
      ],
    },
    {
      range: '新北市',
      county: '65000',
      town: null,
      vill: null,
      type: 'party', // 人工驗證資料用，並未直接用在地圖上
      profRate: 56.6,
      candidates: [
        {
          candNo: '1',
          party: '合一行動聯盟',
          tksRate: 0.17,
          candVictor: ' ',
          tks: 2367,
        },
        {
          candNo: '2',
          party: '中華統一促進黨',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 451,
        },
        {
          candNo: '3',
          party: '親民黨',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 386,
        },
        {
          candNo: '4',
          party: '安定力量',
          tksRate: 0.02,
          candVictor: ' ',
          tks: 256,
        },
        {
          candNo: '5',
          party: '台灣基進',
          tksRate: 0.18,
          candVictor: ' ',
          tks: 2425,
        },
        {
          candNo: '6',
          party: '時代力量',
          tksRate: 42.29,
          candVictor: '*',
          tks: 575590,
        },
      ],
    },
  ],
}
