export const mockData = {
  summary: {
    range: '全國',
    county: null,
    town: null,
    vill: null,
    profRate: 80.0,
    agreeRate: 60.9,
    disagreeRate: 39.1,
    adptVictor: 'Y',
  },
  districts: [
    {
      range: '台北市',
      county: '63000',
      town: null,
      vill: null,
      profRate: 80.0,
      agreeRate: 60.9,
      disagreeRate: 39.1,
      adptVictor: 'Y',
    },
    {
      range: '新北市',
      county: '65000',
      town: null,
      vill: null,
      profRate: 80.0,
      agreeRate: 60.9,
      disagreeRate: 39.1,
      adptVictor: 'Y',
    },
    {
      range: '桃園市',
      county: '68000',
      town: null,
      vill: null,
      profRate: 80.0,
      agreeRate: 60.9,
      disagreeRate: 39.1,
      adptVictor: 'Y',
    },
  ],
}
