// [地圖資料] 縣市長 全國層級資料
export const data = {
  updatedAt: '2022-11-26 23:53:49',
  is_started: true,
  is_running: false,
  districts: [
    {
      range: '臺北市',
      county: '63000',
      town: null,
      vill: null,
      profRate: 67.7,
      candidates: [
        {
          candNo: '1',
          name: '張家豪',
          party: '台灣動物保護黨',
          tksRate: 0.17,
          candVictor: ' ',
          tks: 2367,
        },
        {
          candNo: '2',
          name: '王文娟',
          party: '無黨籍',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 451,
        },
        {
          candNo: '3',
          name: '鄭匡宇',
          party: '無黨籍',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 386,
        },
        {
          candNo: '4',
          name: '黃聖峰',
          party: '台澎黨',
          tksRate: 0.02,
          candVictor: ' ',
          tks: 256,
        },
        {
          candNo: '5',
          name: '童文薰',
          party: '無黨籍',
          tksRate: 0.18,
          candVictor: ' ',
          tks: 2425,
        },
        {
          candNo: '6',
          name: '蔣萬安',
          party: '中國國民黨',
          tksRate: 42.29,
          candVictor: '*',
          tks: 575590,
        },
        {
          candNo: '7',
          name: '蘇煥智',
          party: '台灣維新',
          tksRate: 0.14,
          candVictor: ' ',
          tks: 1851,
        },
        {
          candNo: '8',
          name: '黃珊珊',
          party: '無黨籍',
          tksRate: 25.14,
          candVictor: ' ',
          tks: 342141,
        },
        {
          candNo: '9',
          name: '施奉先',
          party: '無黨籍',
          tksRate: 0.03,
          candVictor: ' ',
          tks: 383,
        },
        {
          candNo: '10',
          name: '唐新民',
          party: '無黨籍',
          tksRate: 0.02,
          candVictor: ' ',
          tks: 316,
        },
        {
          candNo: '11',
          name: '謝立康',
          party: '無黨籍',
          tksRate: 0.02,
          candVictor: ' ',
          tks: 227,
        },
        {
          candNo: '12',
          name: '陳時中',
          party: '民主進步黨',
          tksRate: 31.93,
          candVictor: ' ',
          tks: 434558,
        },
      ],
    },
    {
      range: '新北市',
      county: '65000',
      town: null,
      vill: null,
      profRate: 56.6,
      candidates: [
        {
          candNo: '1',
          name: '林佳龍',
          party: '民主進步黨',
          tksRate: 37.58,
          candVictor: ' ',
          tks: 693976,
        },
        {
          candNo: '2',
          name: '侯友宜',
          party: '中國國民黨',
          tksRate: 62.42,
          candVictor: '*',
          tks: 1152555,
        },
      ],
    },
    {
      range: '桃園市',
      county: '68000',
      town: null,
      vill: null,
      profRate: 59.46,
      candidates: [
        {
          candNo: '1',
          name: '張善政',
          party: '中國國民黨',
          tksRate: 52.02,
          candVictor: '*',
          tks: 557572,
        },
        {
          candNo: '2',
          name: '賴香伶',
          party: '台灣民眾黨',
          tksRate: 5.12,
          candVictor: ' ',
          tks: 54926,
        },
        {
          candNo: '3',
          name: '鄭運鵬',
          party: '民主進步黨',
          tksRate: 40.03,
          candVictor: ' ',
          tks: 428983,
        },
        {
          candNo: '4',
          name: '鄭寶清',
          party: '無黨籍',
          tksRate: 2.83,
          candVictor: ' ',
          tks: 30282,
        },
      ],
    },
    {
      range: '臺中市',
      county: '66000',
      town: null,
      vill: null,
      profRate: 60.01,
      candidates: [
        {
          candNo: '1',
          name: '陳美妃',
          party: '無黨籍',
          tksRate: 1.72,
          candVictor: ' ',
          tks: 23140,
        },
        {
          candNo: '2',
          name: '蔡其昌',
          party: '民主進步黨',
          tksRate: 38.93,
          candVictor: ' ',
          tks: 524224,
        },
        {
          candNo: '3',
          name: '盧秀燕',
          party: '中國國民黨',
          tksRate: 59.35,
          candVictor: '*',
          tks: 799107,
        },
      ],
    },
  ],
}
