export const data = {
  updatedAt: '2024-10-26 23:53:49',
  year: '2024',
  type: 'legislator-district',
  title: '立法委員選舉（台北市）',
  version: 'v2',
  districts: [
    {
      districtName: '01',
      candidates: [
        {
          candNo: '1',
          name: {
            label: '林瑞霞',
            href: 'https://whoareyou.readr.tw/person/37403',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/37403.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 1958,
          tksRate: 3.88,
          candVictor: false,
        },
        {
          candNo: '2',
          name: {
            label: '蔡永泉',
            href: 'https://whoareyou.readr.tw/person/36789',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36789.jpg',
          },
          party: { label: '台灣團結聯盟', href: '', imgSrc: '' },
          tks: 2188,
          tksRate: 4.33,
          candVictor: false,
        },
        {
          candNo: '3',
          name: {
            label: '張榮藏',
            href: 'https://whoareyou.readr.tw/person/39661',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/39661.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2892,
          tksRate: 5.73,
          candVictor: true,
        },
        {
          candNo: '4',
          name: {
            label: '陳家平',
            href: 'https://whoareyou.readr.tw/person/40212',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40212.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3947,
          tksRate: 7.81,
          candVictor: true,
        },
        {
          candNo: '5',
          name: {
            label: '傅大偉',
            href: 'https://whoareyou.readr.tw/person/36788',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36788.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 5054,
          tksRate: 10.01,
          candVictor: true,
        },
        {
          candNo: '6',
          name: {
            label: '黃盈智',
            href: 'https://whoareyou.readr.tw/person/40214',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40214.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4259,
          tksRate: 8.43,
          candVictor: true,
        },
        {
          candNo: '7',
          name: {
            label: '郭文居',
            href: 'https://whoareyou.readr.tw/person/36551',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36551.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2437,
          tksRate: 4.82,
          candVictor: false,
        },
        {
          candNo: '8',
          name: {
            label: '凌子楚',
            href: 'https://whoareyou.readr.tw/person/36786',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36786.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 2447,
          tksRate: 4.84,
          candVictor: false,
        },
        {
          candNo: '9',
          name: {
            label: '梁樹綸',
            href: 'https://whoareyou.readr.tw/person/43563',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43563.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 2524,
          tksRate: 5.0,
          candVictor: false,
        },
        {
          candNo: '10',
          name: {
            label: '郭定緯',
            href: 'https://whoareyou.readr.tw/person/43562',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43562.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3404,
          tksRate: 6.74,
          candVictor: true,
        },
        {
          candNo: '11',
          name: {
            label: '黃露慧',
            href: 'https://whoareyou.readr.tw/person/40211',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40211.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4292,
          tksRate: 8.5,
          candVictor: true,
        },
        {
          candNo: '12',
          name: {
            label: '林昱孜',
            href: 'https://whoareyou.readr.tw/person/43564',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43564.jpg',
          },
          party: { label: '台灣民眾黨', href: '', imgSrc: '' },
          tks: 870,
          tksRate: 1.72,
          candVictor: false,
        },
        {
          candNo: '13',
          name: {
            label: '張敏琪',
            href: 'https://whoareyou.readr.tw/person/40217',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40217.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 3438,
          tksRate: 6.81,
          candVictor: true,
        },
        {
          candNo: '14',
          name: {
            label: '顏色不分藍綠支持性專區顏色田慎節',
            href: 'https://whoareyou.readr.tw/person/43565',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43565.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2813,
          tksRate: 5.57,
          candVictor: true,
        },
        {
          candNo: '15',
          name: {
            label: '吳家慧',
            href: 'https://whoareyou.readr.tw/person/43566',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43566.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 486,
          tksRate: 0.96,
          candVictor: false,
        },
        {
          candNo: '16',
          name: {
            label: '翁渙瑤',
            href: 'https://whoareyou.readr.tw/person/43561',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43561.jpg',
          },
          party: { label: '台灣基進', href: '', imgSrc: '' },
          tks: 1350,
          tksRate: 2.67,
          candVictor: false,
        },
        {
          candNo: '17',
          name: {
            label: '李奕德',
            href: 'https://whoareyou.readr.tw/person/40215',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40215.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2771,
          tksRate: 5.49,
          candVictor: true,
        },
        {
          candNo: '18',
          name: {
            label: '戴寧',
            href: 'https://whoareyou.readr.tw/person/36787',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/36787.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 3382,
          tksRate: 6.7,
          candVictor: true,
        },
      ],
    },
    {
      districtName: '02',
      candidates: [
        {
          candNo: '1',
          name: {
            label: '李忠曆',
            href: 'https://whoareyou.readr.tw/person/40223',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40223.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2811,
          tksRate: 4.42,
          candVictor: true,
        },
        {
          candNo: '2',
          name: {
            label: '黃大祐',
            href: 'https://whoareyou.readr.tw/person/40232',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40232.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4223,
          tksRate: 6.64,
          candVictor: true,
        },
        {
          candNo: '3',
          name: {
            label: '黃敏修',
            href: 'https://whoareyou.readr.tw/person/43572',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43572.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 4372,
          tksRate: 6.88,
          candVictor: true,
        },
        {
          candNo: '4',
          name: {
            label: '蘇澤峰',
            href: 'https://whoareyou.readr.tw/person/40227',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40227.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 3502,
          tksRate: 5.51,
          candVictor: true,
        },
        {
          candNo: '5',
          name: {
            label: '許明對',
            href: 'https://whoareyou.readr.tw/person/27418',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/27418.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 1055,
          tksRate: 1.66,
          candVictor: false,
        },
        {
          candNo: '6',
          name: {
            label: '洪瑋庭',
            href: 'https://whoareyou.readr.tw/person/43567',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43567.jpg',
          },
          party: { label: '台灣基進', href: '', imgSrc: '' },
          tks: 1891,
          tksRate: 2.97,
          candVictor: false,
        },
        {
          candNo: '7',
          name: {
            label: '張閔舜',
            href: 'https://whoareyou.readr.tw/person/43569',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43569.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 1691,
          tksRate: 2.66,
          candVictor: false,
        },
        {
          candNo: '8',
          name: {
            label: '王浩',
            href: 'https://whoareyou.readr.tw/person/38348',
            imgSrc: 'https://2022.npp.vote/api/v1/attachment/47',
          },
          party: { label: '時代力量', href: '', imgSrc: '' },
          tks: 2732,
          tksRate: 4.3,
          candVictor: true,
        },
        {
          candNo: '9',
          name: {
            label: '蘇慶良',
            href: 'https://whoareyou.readr.tw/person/40237',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40237.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 961,
          tksRate: 1.51,
          candVictor: false,
        },
        {
          candNo: '10',
          name: {
            label: '莊豐安',
            href: 'https://whoareyou.readr.tw/person/40238',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40238.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2348,
          tksRate: 3.69,
          candVictor: false,
        },
        {
          candNo: '11',
          name: {
            label: '林煒軒',
            href: 'https://whoareyou.readr.tw/person/43568',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43568.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 3822,
          tksRate: 6.01,
          candVictor: true,
        },
        {
          candNo: '12',
          name: {
            label: '陳品蓁',
            href: 'https://whoareyou.readr.tw/person/13897',
            imgSrc: '',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 888,
          tksRate: 1.4,
          candVictor: false,
        },
        {
          candNo: '13',
          name: {
            label: '張秀華',
            href: 'https://whoareyou.readr.tw/person/40228',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40228.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 5896,
          tksRate: 9.27,
          candVictor: true,
        },
        {
          candNo: '14',
          name: {
            label: '孫貫志',
            href: 'https://whoareyou.readr.tw/person/40240',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40240.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 3146,
          tksRate: 4.95,
          candVictor: true,
        },
        {
          candNo: '15',
          name: {
            label: '林雪峰',
            href: 'https://whoareyou.readr.tw/person/40242',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40242.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 2036,
          tksRate: 3.2,
          candVictor: false,
        },
        {
          candNo: '16',
          name: {
            label: '陳姿妏',
            href: 'https://whoareyou.readr.tw/person/40234',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40234.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 3452,
          tksRate: 5.43,
          candVictor: true,
        },
        {
          candNo: '17',
          name: {
            label: '李錦洋',
            href: 'https://whoareyou.readr.tw/person/43570',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43570.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 1635,
          tksRate: 2.57,
          candVictor: false,
        },
        {
          candNo: '18',
          name: {
            label: '黃思婷',
            href: 'https://whoareyou.readr.tw/person/40222',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40222.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 4318,
          tksRate: 6.79,
          candVictor: true,
        },
        {
          candNo: '19',
          name: {
            label: '蔡文旭',
            href: 'https://whoareyou.readr.tw/person/40239',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40239.jpg',
          },
          party: { label: '民主進步黨', href: '', imgSrc: '' },
          tks: 3029,
          tksRate: 4.76,
          candVictor: true,
        },
        {
          candNo: '20',
          name: {
            label: '鄭光宏',
            href: 'https://whoareyou.readr.tw/person/40241',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/40241.jpg',
          },
          party: { label: '中國國民黨', href: '', imgSrc: '' },
          tks: 4855,
          tksRate: 7.64,
          candVictor: true,
        },
        {
          candNo: '21',
          name: {
            label: '王冠鈞',
            href: 'https://whoareyou.readr.tw/person/12528',
            imgSrc: '',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 1936,
          tksRate: 3.05,
          candVictor: false,
        },
        {
          candNo: '22',
          name: {
            label: '蔡坤叡',
            href: 'https://whoareyou.readr.tw/person/43571',
            imgSrc: 'https://whoareyou-gcs.readr.tw/person/43571.jpg',
          },
          party: { label: '無黨籍', href: '', imgSrc: '' },
          tks: 2977,
          tksRate: 4.68,
          candVictor: true,
        },
      ],
    },
  ],
}
